var restuarants = [
    {name: 'Casa Reveles',
    dineIn: 'yes',
    genre: 'mexican',
    image: '',
    },
    {name: `Denny's`,
    dineIn: 'yes',
    genre: 'burgers',
    image: '',
    },
    {name: 'Dominoes',
    dineIn: 'no',
    genre: 'fastFood',
    image: '',
    },
    {name: 'Jersey Mikes',
    dineIn: 'no',
    genre: 'other',
    image: '',
    },
    {name: 'La Cocina',
    dineIn: 'yes',
    genre: 'mexican',
    image: '',
    },
    {name: 'Los Rancheros',
    dineIn: 'no',
    genre: 'mexican',
    image: '',
    },
    {name: 'L&L Hawaiian BBQ',
    dineIn: 'yes',
    genre: 'other',
    image: '',
    },
    {name: 'Mananas',
    dineIn: 'yes',
    genre: 'mexican',
    image: '',
    },
    {name: 'Panda Express',
    dineIn: 'no',
    genre: 'fastFood',
    image: '',
    },
    {name: `Pete's BBQ`,
    dineIn: 'yes',
    genre: 'other',
    image: '',
    },
    {name: 'Pinto Thai',
    dineIn: 'yes',
    genre: 'asian',
    image: '',
    },
    {name: 'Popeyes',
    dineIn: 'no',
    genre: 'fastFood',
    image: '',
    },
    {name: 'Ramona Noodle House',
    dineIn: 'yes',
    genre: 'asian',
    image: '',
    },
    {name: `Sofie's Pita`,
    dineIn: 'yes',
    genre: 'other',
    image: '',
    },
    {name: 'The Barn',
    dineIn: 'yes',
    genre: 'burgers',
    image: '',
    },
    {name: 'Vibes Sushi Bar and Grill',
    dineIn: 'yes',
    genre: 'asian',
    image: '',
    },
    {name: `Wendy's`,
    dineIn: 'no',
    genre: 'fastFood',
    image: '',
    },
]

